### ISSUE TITLE
HDBPP_ES_VERSION instead of HDBPP_CM_VERSION

### ISSUE THREAD

**Issue by gscalamera** [tango-controls-hdbpp/hdbpp-timescale-project#15]
https://github.com/tango-controls-hdbpp/hdbpp-timescale-project/blob/ae695723e8c8c343d776dd5d81e57f4fb1adc47a/CMakeLists.txt#L66

**Comment by chedburgh** [comment]
Well spotted, and good to see someone using this build system! Its possible to copy this entire project template for the other back ends, i.e. mysql, if you want to.

This will be a problem now the hdbpp-cm has merged the integrated build branch. Slipped through before due to both using the same named branch. 

Create a PR and lets fix it.

**Comment by gscalamera** [comment]
> Its possible to copy this entire project template for the other back ends, i.e. mysql, if you want to.

Yes, I've already prepared a prototype for that

**Comment by chedburgh** [comment]
For your prototype. 

Ensure hdbpp-cs and hdbpp-es get tagged correctly (v2.0.0), and libhdbpp tag gets fixed, then set your build system to them tags. It should just pull the correct versions from github and build them (you can use a branch also in the interim). Its vital some modern practices are used to maintain the dependent repositories for the integrated build system to work.

Any problems, create a GitHub repo and mention me, I will try help if I can.

**Comment by chedburgh** [comment]
Quickly fixed this in the last commit to try bring the build back to functional.
